### ISSUE TITLE
Exceptions in Windows

### ISSUE THREAD

**Issue by Yegorov** [kootenpv/requests_viewer#1]
In Windows 8 (Python 3.5) i have exceptions:

```
>>>view_diff_tree(tree1, tree2)
From t1 to t2, 16.0 insertions and 15.0 deleted
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python351\lib\site-packages\requests_viewer\web.py", line 40, in view_diff_tree
    view_diff(html1, html2, tree1, tree2, url, diff_method)
  File "C:\Python351\lib\site-packages\requests_viewer\web.py", line 63, in view_diff
    view_html(diff)
  File "C:\Python351\lib\site-packages\requests_viewer\web.py", line 22, in view_html
    with open(fname, 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/-4911189448363216856.html'
>>> view_diff_tree(tree1, tree2)
From t1 to t2, 16.0 insertions and 15.0 deleted
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python351\lib\site-packages\requests_viewer\web.py", line 40, in view_diff_tree
    view_diff(html1, html2, tree1, tree2, url, diff_method)
  File "C:\Python351\lib\site-packages\requests_viewer\web.py", line 63, in view_diff
    view_html(diff)
  File "C:\Python351\lib\site-packages\requests_viewer\web.py", line 22, in view_html
    with open(fname, 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/-4911189448363216856.html'
```

also bug fix, i see

```
>>> view_diff_tree(tree1, tree2)
From t1 to t2, 830.0 insertions and 130.0 deleted
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python351\lib\site-packages\requests_viewer\web.py", line 40, in view_diff_tree
    view_diff(html1, html2, tree1, tree2, url, diff_method)
  File "C:\Python351\lib\site-packages\requests_viewer\web.py", line 63, in view_diff
    view_html(diff)
  File "C:\Python351\lib\site-packages\requests_viewer\web.py", line 23, in view_html
    f.write(x)
  File "C:\Python351\lib\encodings\cp1251.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 15259-15261: character maps to <undefined>
```

Maybe in file web.py need change function view_html (line 21):

``` python
import os
# other code
def view_html(x):
    dir_path = './tmp/'
    if not os.path.exists(dir_path):
        os.mkdir(dir_path)
    fname = dir_path + str(hash(x)) + '.html'
    with open(fname, 'w', encoding='utf-8') as f:
        f.write(x)
    webbrowser.open('file://' + os.path.abspath(fname))
    time.sleep(1)
```

**Comment by kootenpv** [comment]
I'm thinking it probably has to do with `/tmp/` not being accessible in Windows.

I rewrote it using tempfile, could you please give it another shot on Windows?

To update to requests_viewer-0.0.4, please run:

```
pip install -U requests_viewer
```

**Comment by Yegorov** [comment]
`tempfile` in Windows сreate files such `C:\Users\Admin\AppData\Local\Temp\tmp42atxfkr`, and as if all should work, but:
- in this (web.py line 23) `with tempfile.NamedTemporaryFile(mode="w") as f:` after leaving the context file removed. Maybe add argument `delete=False` [see](https://docs.python.org/3.5/library/tempfile.html#tempfile.NamedTemporaryFile).
- also file named as `C:\Users\Admin\AppData\Local\Temp\tmp42atxfkr` not associable with html (not extension `*.html`) browser open's as plain text.
- and maybe add argument `encoding='utf-8'` in file's functions.

**Comment by kootenpv** [comment]
Thanks for taking the time to test!
- Why do you need to keep the file alive? It should open once in the webbrowser; after being loaded it should be allowed to be deleted? Or do you really prefer it to be just deleted when  Temp gets cleaned up?
- I tested this, and I suppose you are not using Chrome browser? In my case, the browser inferred it regardless of extension.
- I will add allowing a different encoding to the to-do list.

**Comment by Yegorov** [comment]
> Why do you need to keep the file alive? It should open once in the webbrowser; after being loaded it should be allowed to be deleted? Or do you really prefer it to be just deleted when Temp gets cleaned up?

I use Firefox and when `tempfile.NamedTemporaryFile`  argument `delete=True`, browser does not have time to open a file (likely, `webbrowser.open` is asynchronous function).

Ok, see some examples:
1. 

``` python
def view_html(x):
    with tempfile.NamedTemporaryFile(mode="w") as f:
        f.write(x)
        webbrowser.open('file://' + f.name)
        time.sleep(1)
```

![requests_viewer_1](https://cloud.githubusercontent.com/assets/2566462/17278750/eb6e6ff8-576c-11e6-8880-7c3fea2b28e4.gif)

2.

``` python
def view_html(x):
    with tempfile.NamedTemporaryFile(mode="w", suffix='.html') as f:
        f.write(x)
        webbrowser.open('file://' + f.name)
        time.sleep(1)
```

![requests_viewer_2](https://cloud.githubusercontent.com/assets/2566462/17278752/f1f0b610-576c-11e6-94d2-5a23cba126c2.gif)

3.

``` python
def view_html(x):
    import os
    a = []
    with tempfile.NamedTemporaryFile(mode="w", suffix='.html', delete=False) as f:
        f.write(x)
        f.flush()
        a.append(f.name)
        webbrowser.open('file://' + f.name)
        time.sleep(1)
    for i in a:
        os.remove(i)
```

![requests_viewer_3](https://cloud.githubusercontent.com/assets/2566462/17278754/f793a7e4-576c-11e6-81f4-c6fdc725dc74.gif)

Perhaps there is a way not to write a web page to a file, and directly transfer content browser?

**Comment by kootenpv** [comment]
Thanks for the added gifs!

But I think you should not want to refresh the page? They're loaded; so why refresh?

I have tried to avoid writing to file, but `webbrowser` only reads from file. StringIO would be an option, but hey perhaps indeed why not let the files live.... Temp should be cleaned up after restart. Would you prefer that?

**Comment by kootenpv** [comment]
I actually made a new build involving `delete=False`. It runs smoothly then, doesn't it? When you feel this issue has been resolved, feel free to close it.

**Comment by Yegorov** [comment]
> It runs smoothly then, doesn't it?

Unfortunately no.
Likely, need to add `suffix='.html'` argument to `tempfile.NamedTemporaryFile` and `f.flush()`.

``` python
def view_html(x):
    with tempfile.NamedTemporaryFile(mode="w", suffix='.html', delete=False) as f:
        f.write(x)
        f.flush()
        webbrowser.open('file://' + f.name)
        time.sleep(1)
```

**Comment by Yegorov** [comment]
It works now. Thanks!
